eureka:
  client:
    service-url:
      defaultZone: http://localhost:5001/eureka/,http://localhost:5002/eureka/
  instance:
    hostname: 192.168.0.112

spring:
  application:
    name: fund
  profiles:
    active: peer2