eureka:
  client:
    service-url:
      defaultZone: http://localhost:5001/eureka/
      #,http://localhost:5002/eureka/
  instance:
    hostname: localhost

spring:
  application:
    name: product
  profiles:
    active: peer1

ribbon:
  ConnectTimeout: 5000